-- V13__seed_full_role_permission_matrix.sql
-- Seed complete 208-entry Role × Screen Permissions Matrix for all 16 roles across all 13 modules

INSERT INTO cims_role_permissions (id, role_code, screen_name, can_view, can_create, can_edit, can_approve, can_delete) VALUES
-- 1. SYSADMIN (Full administrative and operational access)
('perm-sys-1', 'SYSADMIN', 'Dashboard', true, true, true, true, true),
('perm-sys-2', 'SYSADMIN', 'Customers', true, true, true, true, true),
('perm-sys-3', 'SYSADMIN', 'Facilities', true, true, true, true, true),
('perm-sys-4', 'SYSADMIN', 'Collateral', true, true, true, true, true),
('perm-sys-5', 'SYSADMIN', 'Insurance', true, true, true, true, true),
('perm-sys-6', 'SYSADMIN', 'Approvals', true, true, true, true, true),
('perm-sys-7', 'SYSADMIN', 'Exceptions', true, true, true, true, true),
('perm-sys-8', 'SYSADMIN', 'Documents', true, true, true, true, true),
('perm-sys-9', 'SYSADMIN', 'Reports', true, true, true, true, true),
('perm-sys-10', 'SYSADMIN', 'Audit Trail', true, true, true, true, true),
('perm-sys-11', 'SYSADMIN', 'Notifications', true, true, true, true, true),
('perm-sys-12', 'SYSADMIN', 'Administration', true, true, true, true, true),
('perm-sys-13', 'SYSADMIN', 'CBS Simulator', true, true, true, true, true),

-- 2. EXEC (Executive oversight, high-level reporting and approvals)
('perm-exec-1', 'EXEC', 'Dashboard', true, false, false, false, false),
('perm-exec-2', 'EXEC', 'Customers', true, false, false, false, false),
('perm-exec-3', 'EXEC', 'Facilities', true, false, false, false, false),
('perm-exec-4', 'EXEC', 'Collateral', true, false, false, false, false),
('perm-exec-5', 'EXEC', 'Insurance', true, false, false, false, false),
('perm-exec-6', 'EXEC', 'Approvals', true, false, false, true, false),
('perm-exec-7', 'EXEC', 'Exceptions', true, false, false, true, false),
('perm-exec-8', 'EXEC', 'Documents', true, false, false, false, false),
('perm-exec-9', 'EXEC', 'Reports', true, false, false, false, false),
('perm-exec-10', 'EXEC', 'Audit Trail', true, false, false, false, false),
('perm-exec-11', 'EXEC', 'Notifications', true, false, false, false, false),
('perm-exec-12', 'EXEC', 'Administration', false, false, false, false, false),
('perm-exec-13', 'EXEC', 'CBS Simulator', false, false, false, false, false),

-- 3. SRMGMT (Senior Management Lead)
('perm-srmgmt-1', 'SRMGMT', 'Dashboard', true, false, false, false, false),
('perm-srmgmt-2', 'SRMGMT', 'Customers', true, false, false, false, false),
('perm-srmgmt-3', 'SRMGMT', 'Facilities', true, false, false, false, false),
('perm-srmgmt-4', 'SRMGMT', 'Collateral', true, false, false, false, false),
('perm-srmgmt-5', 'SRMGMT', 'Insurance', true, false, false, false, false),
('perm-srmgmt-6', 'SRMGMT', 'Approvals', true, false, false, true, false),
('perm-srmgmt-7', 'SRMGMT', 'Exceptions', true, false, false, true, false),
('perm-srmgmt-8', 'SRMGMT', 'Documents', true, false, false, false, false),
('perm-srmgmt-9', 'SRMGMT', 'Reports', true, false, false, false, false),
('perm-srmgmt-10', 'SRMGMT', 'Audit Trail', true, false, false, false, false),
('perm-srmgmt-11', 'SRMGMT', 'Notifications', true, false, false, false, false),
('perm-srmgmt-12', 'SRMGMT', 'Administration', false, false, false, false, false),
('perm-srmgmt-13', 'SRMGMT', 'CBS Simulator', false, false, false, false, false),

-- 4. HODEPT (Head Office Department Head)
('perm-hodept-1', 'HODEPT', 'Dashboard', true, false, false, false, false),
('perm-hodept-2', 'HODEPT', 'Customers', true, false, false, false, false),
('perm-hodept-3', 'HODEPT', 'Facilities', true, false, false, false, false),
('perm-hodept-4', 'HODEPT', 'Collateral', true, false, true, true, false),
('perm-hodept-5', 'HODEPT', 'Insurance', true, false, true, true, false),
('perm-hodept-6', 'HODEPT', 'Approvals', true, false, false, true, false),
('perm-hodept-7', 'HODEPT', 'Exceptions', true, false, true, true, false),
('perm-hodept-8', 'HODEPT', 'Documents', true, true, true, false, false),
('perm-hodept-9', 'HODEPT', 'Reports', true, false, false, false, false),
('perm-hodept-10', 'HODEPT', 'Audit Trail', true, false, false, false, false),
('perm-hodept-11', 'HODEPT', 'Notifications', true, false, false, false, false),
('perm-hodept-12', 'HODEPT', 'Administration', false, false, false, false, false),
('perm-hodept-13', 'HODEPT', 'CBS Simulator', false, false, false, false, false),

-- 5. DISTDIR (District Director)
('perm-distdir-1', 'DISTDIR', 'Dashboard', true, false, false, false, false),
('perm-distdir-2', 'DISTDIR', 'Customers', true, false, false, false, false),
('perm-distdir-3', 'DISTDIR', 'Facilities', true, false, false, false, false),
('perm-distdir-4', 'DISTDIR', 'Collateral', true, false, true, true, false),
('perm-distdir-5', 'DISTDIR', 'Insurance', true, false, true, true, false),
('perm-distdir-6', 'DISTDIR', 'Approvals', true, false, false, true, false),
('perm-distdir-7', 'DISTDIR', 'Exceptions', true, false, true, true, false),
('perm-distdir-8', 'DISTDIR', 'Documents', true, true, true, false, false),
('perm-distdir-9', 'DISTDIR', 'Reports', true, false, false, false, false),
('perm-distdir-10', 'DISTDIR', 'Audit Trail', true, false, false, false, false),
('perm-distdir-11', 'DISTDIR', 'Notifications', true, false, false, false, false),
('perm-distdir-12', 'DISTDIR', 'Administration', false, false, false, false, false),
('perm-distdir-13', 'DISTDIR', 'CBS Simulator', false, false, false, false, false),

-- 6. BRMGR (Branch Manager - Level 1 Checker)
('perm-brmgr-1', 'BRMGR', 'Dashboard', true, false, false, false, false),
('perm-brmgr-2', 'BRMGR', 'Customers', true, false, true, true, false),
('perm-brmgr-3', 'BRMGR', 'Facilities', true, false, false, false, false),
('perm-brmgr-4', 'BRMGR', 'Collateral', true, false, true, true, false),
('perm-brmgr-5', 'BRMGR', 'Insurance', true, false, true, true, false),
('perm-brmgr-6', 'BRMGR', 'Approvals', true, false, false, true, false),
('perm-brmgr-7', 'BRMGR', 'Exceptions', true, false, true, true, false),
('perm-brmgr-8', 'BRMGR', 'Documents', true, true, true, true, false),
('perm-brmgr-9', 'BRMGR', 'Reports', true, false, false, false, false),
('perm-brmgr-10', 'BRMGR', 'Audit Trail', true, false, false, false, false),
('perm-brmgr-11', 'BRMGR', 'Notifications', true, false, false, false, false),
('perm-brmgr-12', 'BRMGR', 'Administration', false, false, false, false, false),
('perm-brmgr-13', 'BRMGR', 'CBS Simulator', false, false, false, false, false),

-- 7. SRM (Senior Relationship Manager)
('perm-srm-1', 'SRM', 'Dashboard', true, false, false, false, false),
('perm-srm-2', 'SRM', 'Customers', true, true, true, false, false),
('perm-srm-3', 'SRM', 'Facilities', true, false, false, false, false),
('perm-srm-4', 'SRM', 'Collateral', true, true, true, false, false),
('perm-srm-5', 'SRM', 'Insurance', true, true, true, false, false),
('perm-srm-6', 'SRM', 'Approvals', true, false, false, false, false),
('perm-srm-7', 'SRM', 'Exceptions', true, false, true, false, false),
('perm-srm-8', 'SRM', 'Documents', true, true, true, false, false),
('perm-srm-9', 'SRM', 'Reports', true, false, false, false, false),
('perm-srm-10', 'SRM', 'Audit Trail', false, false, false, false, false),
('perm-srm-11', 'SRM', 'Notifications', true, false, false, false, false),
('perm-srm-12', 'SRM', 'Administration', false, false, false, false, false),
('perm-srm-13', 'SRM', 'CBS Simulator', false, false, false, false, false),

-- 8. BRM (Branch Relationship Manager)
('perm-brm-1', 'BRM', 'Dashboard', true, false, false, false, false),
('perm-brm-2', 'BRM', 'Customers', true, true, true, false, false),
('perm-brm-3', 'BRM', 'Facilities', true, false, false, false, false),
('perm-brm-4', 'BRM', 'Collateral', true, true, true, false, false),
('perm-brm-5', 'BRM', 'Insurance', true, true, true, false, false),
('perm-brm-6', 'BRM', 'Approvals', true, false, false, false, false),
('perm-brm-7', 'BRM', 'Exceptions', true, false, true, false, false),
('perm-brm-8', 'BRM', 'Documents', true, true, true, false, false),
('perm-brm-9', 'BRM', 'Reports', true, false, false, false, false),
('perm-brm-10', 'BRM', 'Audit Trail', false, false, false, false, false),
('perm-brm-11', 'BRM', 'Notifications', true, false, false, false, false),
('perm-brm-12', 'BRM', 'Administration', false, false, false, false, false),
('perm-brm-13', 'BRM', 'CBS Simulator', false, false, false, false, false),

-- 9. CRO (Corporate Relationship Officer - Primary Maker)
('perm-cro-1', 'CRO', 'Dashboard', true, false, false, false, false),
('perm-cro-2', 'CRO', 'Customers', true, true, true, false, false),
('perm-cro-3', 'CRO', 'Facilities', true, false, false, false, false),
('perm-cro-4', 'CRO', 'Collateral', true, true, true, false, false),
('perm-cro-5', 'CRO', 'Insurance', true, true, true, false, false),
('perm-cro-6', 'CRO', 'Approvals', true, false, false, false, false),
('perm-cro-7', 'CRO', 'Exceptions', true, false, true, false, false),
('perm-cro-8', 'CRO', 'Documents', true, true, true, false, false),
('perm-cro-9', 'CRO', 'Reports', true, false, false, false, false),
('perm-cro-10', 'CRO', 'Audit Trail', false, false, false, false, false),
('perm-cro-11', 'CRO', 'Notifications', true, false, false, false, false),
('perm-cro-12', 'CRO', 'Administration', false, false, false, false, false),
('perm-cro-13', 'CRO', 'CBS Simulator', false, false, false, false, false),

-- 10. BRO (Branch Relationship Officer - Maker)
('perm-bro-1', 'BRO', 'Dashboard', true, false, false, false, false),
('perm-bro-2', 'BRO', 'Customers', true, true, true, false, false),
('perm-bro-3', 'BRO', 'Facilities', true, false, false, false, false),
('perm-bro-4', 'BRO', 'Collateral', true, true, true, false, false),
('perm-bro-5', 'BRO', 'Insurance', true, true, true, false, false),
('perm-bro-6', 'BRO', 'Approvals', true, false, false, false, false),
('perm-bro-7', 'BRO', 'Exceptions', true, false, true, false, false),
('perm-bro-8', 'BRO', 'Documents', true, true, true, false, false),
('perm-bro-9', 'BRO', 'Reports', true, false, false, false, false),
('perm-bro-10', 'BRO', 'Audit Trail', false, false, false, false, false),
('perm-bro-11', 'BRO', 'Notifications', true, false, false, false, false),
('perm-bro-12', 'BRO', 'Administration', false, false, false, false, false),
('perm-bro-13', 'BRO', 'CBS Simulator', false, false, false, false, false),

-- 11. MGRCOLLDOC (Manager Collateral & Documentation)
('perm-mgrcolldoc-1', 'MGRCOLLDOC', 'Dashboard', true, false, false, false, false),
('perm-mgrcolldoc-2', 'MGRCOLLDOC', 'Customers', true, false, false, false, false),
('perm-mgrcolldoc-3', 'MGRCOLLDOC', 'Facilities', true, false, false, false, false),
('perm-mgrcolldoc-4', 'MGRCOLLDOC', 'Collateral', true, true, true, true, false),
('perm-mgrcolldoc-5', 'MGRCOLLDOC', 'Insurance', true, true, true, true, false),
('perm-mgrcolldoc-6', 'MGRCOLLDOC', 'Approvals', true, false, false, true, false),
('perm-mgrcolldoc-7', 'MGRCOLLDOC', 'Exceptions', true, false, true, true, false),
('perm-mgrcolldoc-8', 'MGRCOLLDOC', 'Documents', true, true, true, true, true),
('perm-mgrcolldoc-9', 'MGRCOLLDOC', 'Reports', true, false, false, false, false),
('perm-mgrcolldoc-10', 'MGRCOLLDOC', 'Audit Trail', true, false, false, false, false),
('perm-mgrcolldoc-11', 'MGRCOLLDOC', 'Notifications', true, false, false, false, false),
('perm-mgrcolldoc-12', 'MGRCOLLDOC', 'Administration', false, false, false, false, false),
('perm-mgrcolldoc-13', 'MGRCOLLDOC', 'CBS Simulator', false, false, false, false, false),

-- 12. COLLDOCOFF (Collateral & Documentation Officer)
('perm-colldocoff-1', 'COLLDOCOFF', 'Dashboard', true, false, false, false, false),
('perm-colldocoff-2', 'COLLDOCOFF', 'Customers', true, false, false, false, false),
('perm-colldocoff-3', 'COLLDOCOFF', 'Facilities', true, false, false, false, false),
('perm-colldocoff-4', 'COLLDOCOFF', 'Collateral', true, true, true, false, false),
('perm-colldocoff-5', 'COLLDOCOFF', 'Insurance', true, true, true, false, false),
('perm-colldocoff-6', 'COLLDOCOFF', 'Approvals', true, false, false, false, false),
('perm-colldocoff-7', 'COLLDOCOFF', 'Exceptions', true, false, true, false, false),
('perm-colldocoff-8', 'COLLDOCOFF', 'Documents', true, true, true, false, false),
('perm-colldocoff-9', 'COLLDOCOFF', 'Reports', true, false, false, false, false),
('perm-colldocoff-10', 'COLLDOCOFF', 'Audit Trail', false, false, false, false, false),
('perm-colldocoff-11', 'COLLDOCOFF', 'Notifications', true, false, false, false, false),
('perm-colldocoff-12', 'COLLDOCOFF', 'Administration', false, false, false, false, false),
('perm-colldocoff-13', 'COLLDOCOFF', 'CBS Simulator', false, false, false, false, false),

-- 13. COMPLIANCE (Compliance Officer)
('perm-comp-1', 'COMPLIANCE', 'Dashboard', true, false, false, false, false),
('perm-comp-2', 'COMPLIANCE', 'Customers', true, false, false, false, false),
('perm-comp-3', 'COMPLIANCE', 'Facilities', true, false, false, false, false),
('perm-comp-4', 'COMPLIANCE', 'Collateral', true, false, false, false, false),
('perm-comp-5', 'COMPLIANCE', 'Insurance', true, false, false, false, false),
('perm-comp-6', 'COMPLIANCE', 'Approvals', true, false, false, true, false),
('perm-comp-7', 'COMPLIANCE', 'Exceptions', true, true, true, true, false),
('perm-comp-8', 'COMPLIANCE', 'Documents', true, false, false, false, false),
('perm-comp-9', 'COMPLIANCE', 'Reports', true, false, false, false, false),
('perm-comp-10', 'COMPLIANCE', 'Audit Trail', true, false, false, false, false),
('perm-comp-11', 'COMPLIANCE', 'Notifications', true, false, false, false, false),
('perm-comp-12', 'COMPLIANCE', 'Administration', false, false, false, false, false),
('perm-comp-13', 'COMPLIANCE', 'CBS Simulator', false, false, false, false, false),

-- 14. RISK (Risk Management Officer)
('perm-risk-1', 'RISK', 'Dashboard', true, false, false, false, false),
('perm-risk-2', 'RISK', 'Customers', true, false, false, false, false),
('perm-risk-3', 'RISK', 'Facilities', true, false, false, false, false),
('perm-risk-4', 'RISK', 'Collateral', true, false, false, false, false),
('perm-risk-5', 'RISK', 'Insurance', true, false, false, false, false),
('perm-risk-6', 'RISK', 'Approvals', true, false, false, false, false),
('perm-risk-7', 'RISK', 'Exceptions', true, false, true, true, false),
('perm-risk-8', 'RISK', 'Documents', true, false, false, false, false),
('perm-risk-9', 'RISK', 'Reports', true, false, false, false, false),
('perm-risk-10', 'RISK', 'Audit Trail', true, false, false, false, false),
('perm-risk-11', 'RISK', 'Notifications', true, false, false, false, false),
('perm-risk-12', 'RISK', 'Administration', false, false, false, false, false),
('perm-risk-13', 'RISK', 'CBS Simulator', false, false, false, false, false),

-- 15. AUDITOR (Internal Auditor)
('perm-aud-1', 'AUDITOR', 'Dashboard', true, false, false, false, false),
('perm-aud-2', 'AUDITOR', 'Customers', true, false, false, false, false),
('perm-aud-3', 'AUDITOR', 'Facilities', true, false, false, false, false),
('perm-aud-4', 'AUDITOR', 'Collateral', true, false, false, false, false),
('perm-aud-5', 'AUDITOR', 'Insurance', true, false, false, false, false),
('perm-aud-6', 'AUDITOR', 'Approvals', true, false, false, false, false),
('perm-aud-7', 'AUDITOR', 'Exceptions', true, false, false, false, false),
('perm-aud-8', 'AUDITOR', 'Documents', true, false, false, false, false),
('perm-aud-9', 'AUDITOR', 'Reports', true, false, false, false, false),
('perm-aud-10', 'AUDITOR', 'Audit Trail', true, false, false, false, false),
('perm-aud-11', 'AUDITOR', 'Notifications', true, false, false, false, false),
('perm-aud-12', 'AUDITOR', 'Administration', false, false, false, false, false),
('perm-aud-13', 'AUDITOR', 'CBS Simulator', true, false, false, false, false),

-- 16. RDONLY (Read Only Inspector)
('perm-rdonly-1', 'RDONLY', 'Dashboard', true, false, false, false, false),
('perm-rdonly-2', 'RDONLY', 'Customers', true, false, false, false, false),
('perm-rdonly-3', 'RDONLY', 'Facilities', true, false, false, false, false),
('perm-rdonly-4', 'RDONLY', 'Collateral', true, false, false, false, false),
('perm-rdonly-5', 'RDONLY', 'Insurance', true, false, false, false, false),
('perm-rdonly-6', 'RDONLY', 'Approvals', false, false, false, false, false),
('perm-rdonly-7', 'RDONLY', 'Exceptions', true, false, false, false, false),
('perm-rdonly-8', 'RDONLY', 'Documents', true, false, false, false, false),
('perm-rdonly-9', 'RDONLY', 'Reports', true, false, false, false, false),
('perm-rdonly-10', 'RDONLY', 'Audit Trail', false, false, false, false, false),
('perm-rdonly-11', 'RDONLY', 'Notifications', false, false, false, false, false),
('perm-rdonly-12', 'RDONLY', 'Administration', false, false, false, false, false),
('perm-rdonly-13', 'RDONLY', 'CBS Simulator', false, false, false, false, false)

ON CONFLICT (id) DO UPDATE SET
  can_view = EXCLUDED.can_view,
  can_create = EXCLUDED.can_create,
  can_edit = EXCLUDED.can_edit,
  can_approve = EXCLUDED.can_approve,
  can_delete = EXCLUDED.can_delete;
