import React, { useState } from 'react';
import {
  BarChart3,
  FileSpreadsheet,
  FileText,
  Download,
  Calendar,
  Clock,
  Filter,
  CheckCircle,
  Play,
  Mail,
  Plus,
} from 'lucide-react';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  ScheduledReport,
  Customer,
  LoanAccount,
  Collateral,
  InsurancePolicy,
  CimsException,
  AuditLog,
  UserSession,
} from '../../types';
import { DataGrid, ColumnDef } from '../layout/DataGrid';
import { StatusChip } from '../layout/StatusChip';

interface ReportCatalogProps {
  customers: Customer[];
  facilities: LoanAccount[];
  collaterals: Collateral[];
  policies: InsurancePolicy[];
  exceptions: CimsException[];
  auditLogs: AuditLog[];
  scheduledReports: ScheduledReport[];
  currentUser: UserSession;
  onSaveScheduledReport: (report: Partial<ScheduledReport>) => Promise<void>;
}

export const ReportCatalog: React.FC<ReportCatalogProps> = ({
  customers,
  facilities,
  collaterals,
  policies,
  exceptions,
  auditLogs,
  scheduledReports,
  currentUser,
  onSaveScheduledReport,
}) => {
  const [activeTab, setActiveTab] = useState<'catalog' | 'preview' | 'schedules'>('catalog');
  const [selectedReportCode, setSelectedReportCode] = useState('RPT-01');
  const [filterSegment, setFilterSegment] = useState('All');
  const [filterBranch, setFilterBranch] = useState('All');

  // New Schedule Modal
  const [showScheduleModal, setShowScheduleModal] = useState(false);
  const [schedReportName, setSchedReportName] = useState('Daily Expired Policy Alert');
  const [schedCron, setSchedCron] = useState('0 8 * * *');
  const [schedRecipients, setSchedRecipients] = useState('brmgr@bank.com.et, cro@bank.com.et');
  const [schedFormat, setSchedFormat] = useState<'PDF' | 'Excel' | 'CSV'>('PDF');

  const reportDefinitions = [
    { code: 'RPT-01', name: 'Collateral Insurance Coverage Report', desc: 'Detailed collateral valuation, insured amount, coverage %, and coverage gap' },
    { code: 'RPT-02', name: 'Policy Expiry & Renewal Tracking Report', desc: 'Policies due for renewal across 30, 60, 90 day windows with responsible RMs' },
    { code: 'RPT-03', name: 'Underinsured & Uninsured Collateral Report', desc: 'Pledged assets with insurance coverage shortfall or zero insurance' },
    { code: 'RPT-04', name: 'Outstanding Loans vs Collateral Insurance Report', desc: 'Credit facility balances compared against total active collateral insurance' },
    { code: 'RPT-05', name: 'Exception & Policy Breach Register', desc: 'Audit log of all detected system exceptions, SLA statuses, and corrective actions' },
    { code: 'RPT-06', name: 'Maker-Checker Dual Control Audit Report', desc: 'Immutable trail of maker submissions, checker approvals, and return remarks' },
    { code: 'RPT-07', name: 'Insurer Exposure Concentration Report', desc: 'Portfolio concentration and insured sum risk per approved insurance underwriter' },
    { code: 'RPT-08', name: 'Collateral Release Audit Report', desc: 'Authorized collateral release history verifying 0 ETB outstanding balance checklist' },
    { code: 'RPT-09', name: 'Missing Mandatory Documents Report', desc: 'Collateral assets lacking compulsory Title Deeds or Valuation Reports' },
    { code: 'RPT-10', name: 'User Activity & Security Audit Log', desc: 'Granular login, mutation, and document download security activity trail' },
  ];

  // Export handlers
  const handleExportExcel = (data: any[], title: string) => {
    const ws = XLSX.utils.json_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Report');
    XLSX.writeFile(wb, `${title.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.xlsx`);
  };

  const handleExportPdf = (columns: string[], rows: any[][], title: string) => {
    const doc = new jsPDF('landscape');
    doc.setFontSize(14);
    doc.text(`CBAIMS — ${title}`, 14, 15);
    doc.setFontSize(9);
    doc.text(`Generated by: ${currentUser.name} (${currentUser.role}) | Date: ${new Date().toISOString().substring(0, 19)}`, 14, 22);

    autoTable(doc, {
      startY: 26,
      head: [columns],
      body: rows,
      theme: 'grid',
      headStyles: { fillColor: [11, 37, 69] },
      styles: { fontSize: 8 },
    });

    doc.save(`${title.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  // Generate dataset for RPT-01
  const rpt01Data = collaterals.map((c) => {
    const val = c.valuationAmount || 0;
    const ins = c.insuredAmount || 0;
    const gap = Math.max(0, val - ins);
    const pct = val > 0 ? (ins / val) * 100 : 100;
    return {
      'Collateral Code': c.code,
      Description: c.description,
      Category: c.category,
      'Valuation (ETB)': val,
      'Insured Amount (ETB)': ins,
      'Coverage %': `${pct.toFixed(1)}%`,
      'Coverage Gap (ETB)': gap,
      'Insurance Status': c.insuranceStatus || c.status,
      Segment: c.owningSegment,
      Branch: c.branch,
    };
  });

  // Generate dataset for RPT-02
  const rpt02Data = policies.map((p) => {
    const col = collaterals.find((c) => c.id === p.collateralId);
    return {
      'Policy Number': p.policyNumber,
      'Insurer Name': p.insurerName,
      'Coverage Type': p.coverageType,
      'Collateral Code': col?.code || p.collateralId,
      'Insured Amount (ETB)': p.insuredAmount,
      'Expiry Date': p.expiryDate,
      Status: p.status,
    };
  });

  // Generate dataset for RPT-03
  const rpt03Data = collaterals
    .filter((c) => (c.netInsuranceCoveragePct || 0) < 100)
    .map((c) => ({
      'Collateral Code': c.code,
      Description: c.description,
      'Valuation (ETB)': c.valuationAmount,
      'Insured (ETB)': c.insuredAmount || 0,
      'Shortfall (ETB)': (c.valuationAmount || 0) - (c.insuredAmount || 0),
      'Coverage %': `${(c.netInsuranceCoveragePct || 0).toFixed(1)}%`,
      Segment: c.owningSegment,
      Branch: c.branch,
    }));

  const activeReportDef = reportDefinitions.find((r) => r.code === selectedReportCode);

  return (
    <div className="p-6 space-y-6">
      {/* Tabs */}
      <div className="flex border-b border-[#E2E8F0] bg-white px-4 pt-3 rounded-t-lg gap-2">
        <button
          onClick={() => setActiveTab('catalog')}
          className={`pb-3 px-4 text-xs font-semibold border-b-2 flex items-center gap-2 ${
            activeTab === 'catalog' ? 'border-[#102E4A] text-[#102E4A]' : 'border-transparent text-[#5B6472] hover:text-[#101828]'
          }`}
        >
          <BarChart3 className="w-4 h-4" />
          Report Catalog (10 Standard Reports)
        </button>
        <button
          onClick={() => setActiveTab('preview')}
          className={`pb-3 px-4 text-xs font-semibold border-b-2 flex items-center gap-2 ${
            activeTab === 'preview' ? 'border-[#102E4A] text-[#102E4A]' : 'border-transparent text-[#5B6472] hover:text-[#101828]'
          }`}
        >
          <FileSpreadsheet className="w-4 h-4" />
          Interactive Report Viewer & Export ({selectedReportCode})
        </button>
        <button
          onClick={() => setActiveTab('schedules')}
          className={`pb-3 px-4 text-xs font-semibold border-b-2 flex items-center gap-2 ${
            activeTab === 'schedules' ? 'border-[#102E4A] text-[#102E4A]' : 'border-transparent text-[#5B6472] hover:text-[#101828]'
          }`}
        >
          <Clock className="w-4 h-4" />
          Automated Report Schedules ({scheduledReports.length})
        </button>
      </div>

      {/* Tab 1: Catalog */}
      {activeTab === 'catalog' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {reportDefinitions.map((rpt) => (
            <div
              key={rpt.code}
              onClick={() => {
                setSelectedReportCode(rpt.code);
                setActiveTab('preview');
              }}
              className="cims-card p-5 cursor-pointer hover:border-[#3E7AB0] hover:shadow-md transition-all space-y-2 group"
            >
              <div className="flex justify-between items-start">
                <span className="px-2.5 py-1 rounded bg-[#DCE9F5] text-[#102E4A] font-bold text-xs">
                  {rpt.code}
                </span>
                <Play className="w-4 h-4 text-[#5B6472] group-hover:text-[#1F4E7A] transition-colors" />
              </div>
              <h3 className="font-bold text-sm text-[#101828] group-hover:text-[#102E4A]">{rpt.name}</h3>
              <p className="text-xs text-[#5B6472] leading-relaxed">{rpt.desc}</p>
              <div className="pt-2 text-[11px] text-[#1F4E7A] font-semibold flex items-center gap-1">
                <span>Run & Export Report →</span>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Tab 2: Interactive Preview & Export */}
      {activeTab === 'preview' && activeReportDef && (
        <div className="space-y-4">
          {/* Header & Export Bar */}
          <div className="cims-card p-4 flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white">
            <div>
              <div className="flex items-center gap-2">
                <span className="px-2 py-0.5 rounded bg-[#102E4A] text-white font-bold text-xs">{activeReportDef.code}</span>
                <h2 className="text-base font-bold text-[#101828]">{activeReportDef.name}</h2>
              </div>
              <p className="text-xs text-[#5B6472] mt-0.5">{activeReportDef.desc}</p>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => handleExportExcel(rpt01Data, activeReportDef.name)}
                className="btn-secondary py-1.5 px-3 text-xs bg-emerald-50 border-emerald-300 text-emerald-800 hover:bg-emerald-100"
              >
                <FileSpreadsheet className="w-3.5 h-3.5" />
                Export Excel (XLSX)
              </button>
              <button
                onClick={() => {
                  const cols = Object.keys(rpt01Data[0] || {});
                  const rows = rpt01Data.map((d: any) => Object.values(d));
                  handleExportPdf(cols, rows, activeReportDef.name);
                }}
                className="btn-primary py-1.5 px-3 text-xs"
              >
                <Download className="w-3.5 h-3.5" />
                Export PDF Document
              </button>
            </div>
          </div>

          {/* Interactive Data Table Preview */}
          <div className="cims-card overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-[#EFF5FB] border-b border-[#E2E8F0] text-[#5B6472] font-semibold">
                <tr>
                  <th className="p-3">Collateral Code</th>
                  <th className="p-3">Description</th>
                  <th className="p-3">Category</th>
                  <th className="p-3 text-right">Valuation</th>
                  <th className="p-3 text-right">Insured Amount</th>
                  <th className="p-3 text-right">Coverage %</th>
                  <th className="p-3 text-right">Coverage Gap</th>
                  <th className="p-3">Status</th>
                  <th className="p-3">Segment</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E2E8F0]">
                {rpt01Data.map((row, idx) => (
                  <tr key={idx} className="hover:bg-[#EFF5FB]">
                    <td className="p-3 font-semibold text-[#102E4A]">{row['Collateral Code']}</td>
                    <td className="p-3 max-w-xs truncate">{row['Description']}</td>
                    <td className="p-3">{row['Category']}</td>
                    <td className="p-3 text-right tabular-nums">ETB {Number(row['Valuation (ETB)']).toLocaleString()}</td>
                    <td className="p-3 text-right tabular-nums font-semibold">ETB {Number(row['Insured Amount (ETB)']).toLocaleString()}</td>
                    <td className="p-3 text-right tabular-nums font-bold text-emerald-700">{row['Coverage %']}</td>
                    <td className="p-3 text-right tabular-nums text-red-600">ETB {Number(row['Coverage Gap (ETB)']).toLocaleString()}</td>
                    <td className="p-3"><StatusChip label={row['Insurance Status']} /></td>
                    <td className="p-3">{row['Segment']}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Tab 3: Schedules */}
      {activeTab === 'schedules' && (
        <div className="space-y-4">
          <div className="flex justify-between items-center bg-white p-4 rounded-lg border border-[#E2E8F0]">
            <div>
              <h3 className="text-sm font-bold text-[#101828]">Automated Scheduled Reports & Delivery Engine</h3>
              <p className="text-xs text-[#5B6472]">Configure recurring cron schedules and automated email delivery of portfolio audits</p>
            </div>
            <button
              onClick={() => setShowScheduleModal(true)}
              className="btn-primary py-1.5 px-3 text-xs"
            >
              <Plus className="w-3.5 h-3.5" />
              + Schedule New Report
            </button>
          </div>

          <div className="cims-card overflow-hidden">
            <table className="w-full text-left text-xs">
              <thead className="bg-[#EFF5FB] border-b border-[#E2E8F0] text-[#5B6472] font-semibold">
                <tr>
                  <th className="p-3">Report Name</th>
                  <th className="p-3">Cron Cadence</th>
                  <th className="p-3">Recipients Email</th>
                  <th className="p-3">Format</th>
                  <th className="p-3">Last Run</th>
                  <th className="p-3">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E2E8F0]">
                {scheduledReports.map((s) => (
                  <tr key={s.id} className="hover:bg-[#EFF5FB]">
                    <td className="p-3 font-semibold text-[#102E4A]">{s.reportName}</td>
                    <td className="p-3 font-mono text-[#5B6472]">{s.cronSchedule}</td>
                    <td className="p-3 max-w-xs truncate">{s.recipientsJson}</td>
                    <td className="p-3 font-bold text-[#1F4E7A]">{s.format}</td>
                    <td className="p-3">{s.lastRunAt ? s.lastRunAt.replace('T', ' ').substring(0, 16) : 'Pending first run'}</td>
                    <td className="p-3"><StatusChip label={s.active ? 'Active' : 'Paused'} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Schedule Modal */}
      {showScheduleModal && (
        <div className="fixed inset-0 bg-[#102E4A]/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg border border-[#E2E8F0] shadow-xl max-w-md w-full overflow-hidden text-xs">
            <div className="p-4 bg-[#102E4A] text-white flex justify-between items-center">
              <h3 className="text-sm font-bold">Schedule Recurring Report</h3>
              <button onClick={() => setShowScheduleModal(false)} className="text-white hover:text-gray-300">✕</button>
            </div>
            <form
              onSubmit={async (e) => {
                e.preventDefault();
                await onSaveScheduledReport({
                  reportName: schedReportName,
                  cronSchedule: schedCron,
                  recipientsJson: schedRecipients,
                  format: schedFormat,
                  active: true,
                });
                setShowScheduleModal(false);
              }}
              className="p-5 space-y-3"
            >
              <div>
                <label className="block font-semibold text-[#101828] mb-1">Select Report (M)</label>
                <select
                  value={schedReportName}
                  onChange={(e) => setSchedReportName(e.target.value)}
                  className="w-full p-2 border border-[#E2E8F0] rounded"
                >
                  {reportDefinitions.map((r) => (
                    <option key={r.code} value={r.name}>
                      {r.code} — {r.name}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block font-semibold text-[#101828] mb-1">Cron Cadence (M)</label>
                <input
                  type="text"
                  required
                  value={schedCron}
                  onChange={(e) => setSchedCron(e.target.value)}
                  placeholder="e.g. 0 8 * * * (Daily at 08:00 AM)"
                  className="w-full p-2 border border-[#E2E8F0] rounded font-mono"
                />
              </div>

              <div>
                <label className="block font-semibold text-[#101828] mb-1">Recipient Email(s) (M)</label>
                <input
                  type="text"
                  required
                  value={schedRecipients}
                  onChange={(e) => setSchedRecipients(e.target.value)}
                  className="w-full p-2 border border-[#E2E8F0] rounded"
                />
              </div>

              <div>
                <label className="block font-semibold text-[#101828] mb-1">Export Format (M)</label>
                <select
                  value={schedFormat}
                  onChange={(e) => setSchedFormat(e.target.value as any)}
                  className="w-full p-2 border border-[#E2E8F0] rounded"
                >
                  <option value="PDF">PDF Document</option>
                  <option value="Excel">Excel Spreadsheet (XLSX)</option>
                  <option value="CSV">CSV Data File</option>
                </select>
              </div>

              <div className="flex justify-end gap-2 pt-3 border-t border-[#E2E8F0]">
                <button type="button" onClick={() => setShowScheduleModal(false)} className="btn-secondary">
                  Cancel
                </button>
                <button type="submit" className="btn-primary">
                  Save Schedule
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
